// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(PhysioDbContext))]
    [Migration("20211028030350_Adding Treatments To Appointments")]
    partial class AddingTreatmentsToAppointments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Domain.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientRecordId")
                        .HasColumnType("int");

                    b.Property<int>("PlacedById")
                        .HasColumnType("int");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientRecordId");

                    b.HasIndex("PlacedById");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Core.Domain.PatientRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfDismissal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfRegistration")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiagnoseDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiagnoseId")
                        .HasColumnType("int");

                    b.Property<string>("DiagnosticBodyLocalization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosticCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HeadPractitionerId")
                        .HasColumnType("int");

                    b.Property<int>("IntakeHandlerId")
                        .HasColumnType("int");

                    b.Property<int?>("IntakeSupervisorId")
                        .HasColumnType("int");

                    b.Property<string>("MedicalComplaintsDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("TreatmentPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HeadPractitionerId");

                    b.HasIndex("IntakeHandlerId");

                    b.HasIndex("IntakeSupervisorId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.HasIndex("TreatmentPlanId");

                    b.ToTable("PatientRecords");
                });

            modelBuilder.Entity("Core.Domain.People.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PatientImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1978, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "frank@boer.nl",
                            Gender = 0,
                            IdentificationNumber = "425",
                            Name = "Frank de Boer",
                            PhoneNumber = "0643434344",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1996, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mel@Jonge.com",
                            Gender = 1,
                            IdentificationNumber = "2174234",
                            Name = "Melissa de Jonge",
                            PhoneNumber = "0643923744",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1999, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mtdemont@orange.fr",
                            Gender = 0,
                            IdentificationNumber = "2125345",
                            Name = "Mathieu Demontreux",
                            PhoneNumber = "0674054252",
                            Role = 1
                        });
                });

            modelBuilder.Entity("Core.Domain.People.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Workers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Worker");
                });

            modelBuilder.Entity("Core.Domain.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoomNumber = 1,
                            RoomType = "Oefenzaal"
                        },
                        new
                        {
                            Id = 2,
                            RoomNumber = 2,
                            RoomType = "Oefenzaal"
                        },
                        new
                        {
                            Id = 3,
                            RoomNumber = 3,
                            RoomType = "Oefenzaal"
                        },
                        new
                        {
                            Id = 4,
                            RoomNumber = 4,
                            RoomType = "Oefenzaal"
                        },
                        new
                        {
                            Id = 5,
                            RoomNumber = 1,
                            RoomType = "Behandelruimte"
                        },
                        new
                        {
                            Id = 6,
                            RoomNumber = 2,
                            RoomType = "Behandelruimte"
                        },
                        new
                        {
                            Id = 7,
                            RoomNumber = 3,
                            RoomType = "Behandelruimte"
                        },
                        new
                        {
                            Id = 8,
                            RoomNumber = 4,
                            RoomType = "Behandelruimte"
                        });
                });

            modelBuilder.Entity("Core.Domain.Time.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("PractitionerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TreatmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PractitionerId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Core.Domain.Time.Availability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.ToTable("Availabilities");
                });

            modelBuilder.Entity("Core.Domain.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Particularities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientRecordId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentInfoId")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentPerformedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("TreatmentPerformedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientRecordId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TreatmentPerformedById");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("Core.Domain.TreatmentPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SessionDuration")
                        .HasColumnType("int");

                    b.Property<int>("SessionsPerWeek")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TreatmentPlans");
                });

            modelBuilder.Entity("Core.Domain.People.Intern", b =>
                {
                    b.HasBaseType("Core.Domain.People.Worker");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Intern");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Email = "bam.vheng@student.avans.nl",
                            Name = "Bidgret van Hengelo",
                            StudentNumber = "243233"
                        },
                        new
                        {
                            Id = 4,
                            Email = "r.vrij@student.avans.nl",
                            Name = "Rens van Rijen",
                            StudentNumber = "243372"
                        },
                        new
                        {
                            Id = 5,
                            Email = "m.rodriguez@student.avans.nl",
                            Name = "Magdela Rodriguez",
                            StudentNumber = "242331"
                        });
                });

            modelBuilder.Entity("Core.Domain.People.Physiotherapist", b =>
                {
                    b.HasBaseType("Core.Domain.People.Worker");

                    b.Property<string>("BigNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Physiotherapist");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "d.m@docent.avans.nl",
                            Name = "Daniel Marssen",
                            BigNumber = "25632",
                            EmployeeNumber = "302",
                            PhoneNumber = "0653242635"
                        },
                        new
                        {
                            Id = 2,
                            Email = "m.frueger@docent.avans.nl",
                            Name = "Mark Frueger",
                            BigNumber = "27042",
                            EmployeeNumber = "326",
                            PhoneNumber = "0664326365"
                        });
                });

            modelBuilder.Entity("Core.Domain.Comment", b =>
                {
                    b.HasOne("Core.Domain.PatientRecord", "PatientRecord")
                        .WithMany("Comments")
                        .HasForeignKey("PatientRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.People.Worker", "PlacedBy")
                        .WithMany()
                        .HasForeignKey("PlacedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientRecord");

                    b.Navigation("PlacedBy");
                });

            modelBuilder.Entity("Core.Domain.PatientRecord", b =>
                {
                    b.HasOne("Core.Domain.People.Physiotherapist", "HeadPractitioner")
                        .WithMany("HeadPractitioner")
                        .HasForeignKey("HeadPractitionerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.People.Worker", "IntakeHandler")
                        .WithMany("Intake")
                        .HasForeignKey("IntakeHandlerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.People.Physiotherapist", "IntakeSupervisor")
                        .WithMany("Supervisor")
                        .HasForeignKey("IntakeSupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.People.Patient", "Patient")
                        .WithOne("PatientRecord")
                        .HasForeignKey("Core.Domain.PatientRecord", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.TreatmentPlan", "TreatmentPlan")
                        .WithMany()
                        .HasForeignKey("TreatmentPlanId");

                    b.Navigation("HeadPractitioner");

                    b.Navigation("IntakeHandler");

                    b.Navigation("IntakeSupervisor");

                    b.Navigation("Patient");

                    b.Navigation("TreatmentPlan");
                });

            modelBuilder.Entity("Core.Domain.Time.Appointment", b =>
                {
                    b.HasOne("Core.Domain.People.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.People.Worker", "Practitioner")
                        .WithMany()
                        .HasForeignKey("PractitionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Treatment", "Treatment")
                        .WithMany()
                        .HasForeignKey("TreatmentId");

                    b.Navigation("Patient");

                    b.Navigation("Practitioner");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("Core.Domain.Time.Availability", b =>
                {
                    b.HasOne("Core.Domain.People.Worker", "Worker")
                        .WithMany("Availabilities")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Core.Domain.Treatment", b =>
                {
                    b.HasOne("Core.Domain.PatientRecord", "PatientRecord")
                        .WithMany("Treatments")
                        .HasForeignKey("PatientRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.People.Worker", "TreatmentPerformedBy")
                        .WithMany()
                        .HasForeignKey("TreatmentPerformedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientRecord");

                    b.Navigation("Room");

                    b.Navigation("TreatmentPerformedBy");
                });

            modelBuilder.Entity("Core.Domain.PatientRecord", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("Core.Domain.People.Patient", b =>
                {
                    b.Navigation("PatientRecord");
                });

            modelBuilder.Entity("Core.Domain.People.Worker", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("Intake");
                });

            modelBuilder.Entity("Core.Domain.People.Physiotherapist", b =>
                {
                    b.Navigation("HeadPractitioner");

                    b.Navigation("Supervisor");
                });
#pragma warning restore 612, 618
        }
    }
}
